<?php


namespace oop_project;


class Truck extends CarTypes
{
    private $type;
    private $color;
    private $maxSpeed;
    public function __construct($type, $color, $maxSpeed)
    {
        $this->type = $type;
        $this->color = $color;
        $this->maxSpeed = $maxSpeed;
    }

    public function type()
    {
        echo "I am a truck. Model " . $this->type . "\n";// TODO: Change the autogenerated stub
    }

    public function color()
    {
        echo "I am a truck. Color " . $this->color . "\n";// TODO: Change the autogenerated stub
    }

    public function maxSpeed()
    {
        echo "Maximum speed is " . $this->maxSpeed . "\n";
    }

}